baseURL: 'https://tomascostak.github.io/'
languageCode: 'en-us'
title: TomasCostaK
theme: PaperMod
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production 
  title: TomasCostaK Portfolio
  description: Hi, my name is **Tomás** and this is my porfolio and blog. Below you can find some of the work I have produced as well as some of my opinions and investigations on mostly **ML topics**.
  keywords: [Blog, Portfolio, PaperMod, Data Science, ML]
  author: TomasCostaK
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false 

params:
  profileMode:
    enabled: true
    title: Greetings, reader! 👨‍🔬
    subtitle: Hi, my name is **Tomás** and this is my porfolio and blog. Below you can find some of the work I have produced on **Data** and **ML topics**.
    imageUrl: https://avatars.githubusercontent.com/u/24943695?v=4 # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects
        
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/tomascostax/"
    - name: github
      url: "https://github.com/TomasCostaK"
    
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blogs/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2